[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NETLIFY_ANALYTICS = "true"
  # ビルド最適化
  NODE_OPTIONS = "--max-old-space-size=4096"
  # キャッシュ設定
  NETLIFY_CACHE_DIRECTORY = ".netlify/cache"

# Netlify Functions設定
[functions]
  directory = "netlify/functions"

# セキュリティヘッダー
[[headers]]
  for = "/*"
  [headers.values]
  X-Frame-Options = "DENY"
  X-XSS-Protection = "1; mode=block"
  X-Content-Type-Options = "nosniff"
  Referrer-Policy = "strict-origin-when-cross-origin"
  # CSP (Content Security Policy)
  Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; font-src 'self' data:; connect-src 'self';"

# PWA用のヘッダー
[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
  Content-Type = "application/manifest+json"
  Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/sw.js"
  [headers.values]
  Content-Type = "application/javascript"
  Cache-Control = "no-cache"

# 静的アセットのキャッシュ設定
[[headers]]
  for = "/assets/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

# SPAリダイレクト設定
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# プラグイン設定（a11yプラグインはUIで管理）
