[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"

# 基本プラグイン（段階的導入用）
[[plugins]]
package = "@netlify/plugin-cache"
  [plugins.inputs]
  paths = ["node_modules/.cache", ".vite"]

[[plugins]]
package = "@netlify/plugin-headers"
  [plugins.inputs]
  for = "/*"
  [plugins.inputs.values]
  X-Frame-Options = "DENY"
  X-XSS-Protection = "1; mode=block"
  X-Content-Type-Options = "nosniff"

# SPAリダイレクト設定
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
