[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"
  NETLIFY_ANALYTICS = "true"

# Netlify Functions設定
[functions]
  directory = "netlify/functions"

# セキュリティヘッダー
[[headers]]
  for = "/*"
  [headers.values]
  X-Frame-Options = "DENY"
  X-XSS-Protection = "1; mode=block"
  X-Content-Type-Options = "nosniff"
  Referrer-Policy = "strict-origin-when-cross-origin"

# SPAリダイレクト設定
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# プラグイン設定
[[plugins]]
  package = "netlify-plugin-a11y"
  [plugins.inputs]
    timeout = 60000  # タイムアウトを60秒に延長
    concurrency = 1  # 並行実行数を1に制限
