[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"
  NETLIFY_ANALYTICS = "true"

# Netlify Functions設定
[functions]
  directory = "netlify/functions"

# セキュリティヘッダー
[[headers]]
  for = "/*"
  [headers.values]
  X-Frame-Options = "DENY"
  X-XSS-Protection = "1; mode=block"
  X-Content-Type-Options = "nosniff"
  Referrer-Policy = "strict-origin-when-cross-origin"

# SPAリダイレクト設定
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 推奨プラグイン設定（a11yを除く）
[[plugins]]
  package = "netlify-plugin-image-optim"
  [plugins.inputs]
    quality = 80

[[plugins]]
  package = "netlify-plugin-minify-html"
  [plugins.inputs]
    minify_html = true

[[plugins]]
  package = "netlify-plugin-checklinks"
  [plugins.inputs]
    timeout = 30000